export const GET_USER_BALANCE = 'GET_USER_BALANCE';
export const TRANSFER_COIN = 'TRANSFER_COIN';
export const GET_LIST_ADDRESS = 'GET_LIST_ADDRESS';
export const GET_RECENT_ADDRESS = 'GET_RECENT_ADDRESS';
export const DELETE_RECENT_ADDRESS = 'DELETE_RECENT_ADDRESS';
