const context = 'crypto';

export const GET_ALL_COIN_SUCCEED = `GET_ALL_COIN_SUCCEED`;
export const GET_LIMIT_WITHDRAWAL_SUCCEED = `GET_LIMIT_WITHDRAWAL_SUCCEED`;
export const GET_MARKET_SUCCEED = `GET_MARKET_SUCCEED`;
export const GET_COIN_SETTING_SUCCEED = `GET_COIN_SETTING_SUCCEED`;
